### ISSUE TITLE
support variables which each file entry can refer them in the user file and base file.

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/exvar.py#16]
For example,

```yaml
# .exvar.base.yml
config:
  default_prefix: .tmpl.
  default_suffix:
vars:
  $[vm ip]: 192.168.50.4  # define the variable "$[vm ip]"
files:
  ssh_config:
    vars:
      $[vm ip]:
        value: $[vm ip]  # refer the variable "$[vm ip]"
  Vagrantfile:
    vars:
      $[vm ip]:
        value: $[vm ip] # refer the variable "$[vm ip]"
```
